# Generated by Django 5.0.4 on 2024-06-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragonball',
            old_name='level',
            new_name='años',
        ),
        migrations.RenameField(
            model_name='dragonball',
            old_name='number',
            new_name='ki',
        ),
        migrations.RenameField(
            model_name='dragonball',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='dragonball',
            old_name='type',
            new_name='raza',
        ),
    ]
