# Generated by Django 5.0.4 on 2024-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0002_rename_level_dragonball_años_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonball',
            name='años',
            field=models.IntegerField(),
        ),
    ]
