# Generated by Django 5.0.4 on 2024-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0004_rename_nombre_dragonball_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dragonballs', models.ManyToManyField(blank=True, to='dragon_ball.dragonball')),
            ],
        ),
    ]
