# Generated by Django 5.0.4 on 2024-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragonballsaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(max_length=128)),
                ('capitulos', models.IntegerField()),
                ('villano', models.CharField(max_length=128)),
                ('transformaciones', models.IntegerField()),
            ],
        ),
    ]
