# Generated by Django 5.0.4 on 2024-06-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0006_dragonballsaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonballsaga',
            name='villano',
            field=models.BooleanField(default=False),
        ),
    ]
