# Generated by Django 5.0.4 on 2024-06-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0007_alter_dragonballsaga_villano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragonballsaga',
            old_name='personaje',
            new_name='name',
        ),
    ]
