# Generated by Django 5.0.4 on 2024-06-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0009_dragonballvivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dragonballsagas',
            field=models.ManyToManyField(blank=True, to='dragon_ball.dragonballsaga'),
        ),
        migrations.AddField(
            model_name='user',
            name='dragonballvivos',
            field=models.ManyToManyField(blank=True, to='dragon_ball.dragonballvivo'),
        ),
    ]
