# Generated by Django 5.0.4 on 2024-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0010_user_dragonballsagas_user_dragonballvivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragonballsaga',
            name='saga',
            field=models.CharField(default='Default Saga', max_length=100),
        ),
    ]
