# Generated by Django 5.0.4 on 2024-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_ball', '0011_dragonballsaga_saga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonballsaga',
            name='saga',
            field=models.CharField(default='todas', max_length=100),
        ),
    ]
