# Generated by Django 5.0.4 on 2024-06-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_funko_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funko',
            name='is_backlight',
        ),
    ]
